var a=10;
var b=10.5;
var c="hello";
var d=-10;
var e='s';
var f=true;
console.log(typeof(a));
console.log(typeof(b));
console.log(typeof(c));
console.log(typeof(d));
console.log(typeof(e));
console.log(typeof(f));